version: '3.9'

services:
  backend:
    build: ./backend
    container_name: spelling_backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: spelling_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000/api
    restart: unless-stopped

volumes:
  data: